"""Initial migration

Revision ID: 6d15c4163449
Revises: 
Create Date: 2025-05-18 19:18:11.232122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '6d15c4163449'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу пользователей
    op.create_table('users',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('nickname', sa.String(), nullable=True),
        sa.Column('nickname_webapp', sa.String(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('spins_count', sa.Integer(), nullable=True),
        sa.Column('tickets', sa.Integer(), nullable=True),
        sa.Column('last_free_spin', sa.DateTime(), nullable=True),
        sa.Column('referral_count', sa.Integer(), nullable=True),
        sa.Column('referred_by', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем таблицу игр
    op.create_table('games',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('result', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем таблицу статистики
    op.create_table('daily_stats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('total_wins', sa.BigInteger(), nullable=True),
        sa.Column('spins_count', sa.Integer(), nullable=True),
        sa.Column('sector_stats', JSONB(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы
    op.create_index('ix_daily_stats_date', 'daily_stats', ['date'], unique=True)
    op.create_index('idx_daily_stats_total_win', 'daily_stats', ['total_wins'], unique=False)
    
    op.create_index('idx_games_user_id', 'games', ['user_id'], unique=False)
    op.create_index('idx_games_created_at', 'games', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_games_user_id_created_at', 'games', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_games_result', 'games', ['result'], unique=False)
    
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_spins_count', 'users', [sa.text('spins_count DESC')], unique=False)
    op.create_index('idx_users_spins_count_id', 'users', [sa.text('spins_count DESC'), 'id'], unique=False)
    op.create_index('idx_users_spins_count_excl_test', 'users', [sa.text('spins_count DESC')], unique=False, postgresql_where='id != 123456789')
    op.create_index('idx_users_referral_count', 'users', [sa.text('referral_count DESC')], unique=False)
    op.create_index('idx_users_referred_by', 'users', ['referred_by'], unique=False)
    op.create_index('idx_users_referred_by_id', 'users', ['referred_by', 'id'], unique=False)
    op.create_index('idx_users_tickets', 'users', ['tickets'], unique=False)
    op.create_index('idx_users_last_free_spin', 'users', ['last_free_spin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_last_free_spin', table_name='users')
    op.drop_index('idx_users_tickets', table_name='users')
    op.drop_index('idx_users_referred_by_id', table_name='users')
    op.drop_index('idx_users_referred_by', table_name='users')
    op.drop_index('idx_users_referral_count', table_name='users')
    op.drop_index('idx_users_spins_count_excl_test', table_name='users')
    op.drop_index('idx_users_spins_count_id', table_name='users')
    op.drop_index('idx_users_spins_count', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    
    op.drop_index('idx_games_result', table_name='games')
    op.drop_index('idx_games_user_id_created_at', table_name='games')
    op.drop_index('idx_games_created_at', table_name='games')
    op.drop_index('idx_games_user_id', table_name='games')
    
    op.drop_index('idx_daily_stats_total_win', table_name='daily_stats')
    op.drop_index('ix_daily_stats_date', table_name='daily_stats')
    
    op.drop_table('daily_stats')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
